import type { Metadata } from 'next';
import * as Base from '@/components/Base/Index';
import { Noto_Sans_JP } from 'next/font/google';
import '@/public/Styles/app.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';

config.autoAddCss = false;

const notoSansJP = Noto_Sans_JP({
  weight: ['400'],
  subsets: ['latin'],
  style: ['normal'],
});

export const metadata: Metadata = {
  title: 'Yos_sy Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ja'>
      <body className={notoSansJP.className}>
        <Base.Header />
        <Base.Sidebar />
        <main className='main'>{children}</main>
        {/* <layouts.Footer /> */}
      </body>
    </html>
  );
}
